### ISSUE TITLE
uno does not use CANDLE_DATA_DIR when --use_exported_data option is used

### ISSUE THREAD

**Issue by brettin** [ECP-CANDLE/Benchmarks#105]
echo $CANDLE_DATA_DIR 
/homes/brettin/Singularity/workspace/data_dir
ls $CANDLE_DATA_DIR 
uno_input_data.h5

# ERROR MESSAGE (note that I ran uno from /homes/brettin/Singularity/workspace)

OSError: ``/homes/brettin/Singularity/workspace/uno_input_data.h5`` does not exist

# CANDLE_CONFIG

[Global_Params]
train_sources=['CCLE', 'GDSC', 'CTRP', 'ALMANAC']
#export_data='uno_input_data.h5'
use_exported_data='uno_input_data.h5'
test_sources=['train']
cell_types=None
cell_features=['rnaseq']
drug_features=['descriptors']
dense=[1000, 1000, 1000, 1000, 1000]
dense_feature_layers=[1000, 1000, 1000]
activation='relu'
loss='mse'
optimizer='adamax'
scaling='std'
dropout=.1
epochs=1
batch_size=32
val_split=0.2
cv=1
max_val_loss=1.0
learning_rate=0.0001
base_lr=None
agg_dose='AUC'
residual=False
reduce_lr=True
warmup_lr=True
batch_normalization=False
feature_subsample=0
rng_seed=2018
no_gen=False
verbose=False

preprocess_rnaseq='source_scale'
gpus=[0]
use_landmark_genes=True
no_feature_source=True
no_response_source=True
cp=True
save_path='save/uno'
output_dir='output/uno'
single=True
on_memory_loader=True

[Monitor_Params]
timeout=-1

**Comment by jmohdyusof** [comment]
That path it is using does not match CANDLE_DATA_DIR ? (data_dir subdirectory is missing)
Where in the code is the load error coming from? DataLoader has a ton of options

**Comment by jmohdyusof** [comment]
If this is locally exported data, why should it be using CANDLE_DATA_DIR? Should it be output_dir or something else?

**Comment by brettin** [comment]
tested and confirmed.
