### ISSUE TITLE
File creation bug: FileNotFound genotype.json

### ISSUE THREAD

**Issue by yngtodd** [ECP-CANDLE/Benchmarks#65]
Looks like the `DARTS` example fails when a `genotype.json` is not created before saving in the `results/` directory. 

I am assigning myself this issue.

**Comment by yngtodd** [comment]
Hey @jmohdyusof, I am unable to reproduce this error on my `develop` branch. I did take a look at [`default_model.txt: line 4`](https://github.com/ECP-CANDLE/Benchmarks/blob/develop/examples/darts/uno/default_model.txt#L4), where we set the path to write `genotype.json` to `./results`. I am not sure how my fork and the this repo got out of sync there.

**Comment by jmohdyusof** [comment]
I am not sure I understand this? If file paths are consistent, then the example should work regardles of what path I choose, since both the read and write use the same state?

**Comment by yngtodd** [comment]
It looks like the difference is that the DARTS meters check to make sure that the directories in the specified path exist, and, if they do not, the will create them [meters.save](https://github.com/yngtodd/Benchmarks/blob/develop/common/darts/meters/epoch.py#L38). The `GenotypeStorage`, on the other hand, does not. [genotype.save](https://github.com/yngtodd/Benchmarks/blob/develop/common/darts/storage/genotype.py#L26). 

Let me test what changing the genotype storage does when changing that. That way, we would not need to `.gitkeep` in the `results/`.

**Comment by jmohdyusof** [comment]
In uno the results dir never gets created at all. Also, can we rename advanced/example.py to advanced/advanced_example.py (to match uno_example.py)

**Comment by yngtodd** [comment]
I'll close this after the merge. If need be, open this bad boy up.
